export * from "./Day1";
export * from "./Day2";
export * from "./Day3";
export * from "./Day4";
export * from "./Day5";
export * from "./Day6";
export * from "./Day7";
export * from "./Day8";
export * from "./Day9";